# Generated by Django 4.2.2 on 2024-03-22 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='category_title')),
            ],
            options={
                'db_table': 'category',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='salesman_title')),
                ('site', models.CharField(blank=True, max_length=255, null=True, verbose_name='site')),
            ],
            options={
                'db_table': 'salesman',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daten', models.DateTimeField(verbose_name='daten')),
                ('title', models.CharField(max_length=256, verbose_name='news_title')),
                ('details', models.TextField(verbose_name='news_details')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='news_photo')),
            ],
            options={
                'db_table': 'news',
                'ordering': ['daten'],
                'indexes': [models.Index(fields=['daten'], name='news_daten_a29edb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
                ('dateb', models.DateTimeField(verbose_name='dateb')),
                ('salesman', models.CharField(max_length=64, verbose_name='salesman')),
                ('category', models.CharField(max_length=255, verbose_name='category')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('code', models.CharField(max_length=255, verbose_name='code')),
                ('photo_url', models.CharField(max_length=255, verbose_name='photo_url')),
            ],
            options={
                'db_table': 'basket',
                'ordering': ['dateb'],
                'indexes': [models.Index(fields=['dateb'], name='basket_dateb_a545c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
                ('dateb', models.DateTimeField(verbose_name='dateb')),
                ('title', models.CharField(max_length=255, verbose_name='product_title')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('code', models.CharField(max_length=255, verbose_name='code')),
                ('photo_url', models.CharField(max_length=255, verbose_name='photo_url')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='scraping.category')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_salesman', to='scraping.salesman')),
            ],
            options={
                'db_table': 'product',
                'ordering': ['dateb'],
                'indexes': [models.Index(fields=['dateb'], name='product_dateb_23071e_idx'), models.Index(fields=['salesman'], name='product_salesma_9c55d1_idx'), models.Index(fields=['category'], name='product_categor_26b384_idx'), models.Index(fields=['title'], name='product_title_9e36ed_idx')],
            },
        ),
    ]
